/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions';
import { Route as AuthenticatedMetricsRouteImport } from './routes/_authenticated/metrics';
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories';
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge';
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedMetricsRoute = AuthenticatedMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute;
  '/chat': typeof AuthenticatedChatRoute;
  '/knowledge': typeof AuthenticatedKnowledgeRoute;
  '/memories': typeof AuthenticatedMemoriesRoute;
  '/metrics': typeof AuthenticatedMetricsRoute;
  '/sessions': typeof AuthenticatedSessionsRoute;
  '/': typeof AuthenticatedIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/chat': typeof AuthenticatedChatRoute;
  '/knowledge': typeof AuthenticatedKnowledgeRoute;
  '/memories': typeof AuthenticatedMemoriesRoute;
  '/metrics': typeof AuthenticatedMetricsRoute;
  '/sessions': typeof AuthenticatedSessionsRoute;
  '/': typeof AuthenticatedIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/chat': typeof AuthenticatedChatRoute;
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute;
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute;
  '/_authenticated/metrics': typeof AuthenticatedMetricsRoute;
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/login'
    | '/chat'
    | '/knowledge'
    | '/memories'
    | '/metrics'
    | '/sessions'
    | '/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/chat'
    | '/knowledge'
    | '/memories'
    | '/metrics'
    | '/sessions'
    | '/';
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chat'
    | '/_authenticated/knowledge'
    | '/_authenticated/memories'
    | '/_authenticated/metrics'
    | '/_authenticated/sessions'
    | '/_authenticated/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions';
      path: '/sessions';
      fullPath: '/sessions';
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/metrics': {
      id: '/_authenticated/metrics';
      path: '/metrics';
      fullPath: '/metrics';
      preLoaderRoute: typeof AuthenticatedMetricsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/memories': {
      id: '/_authenticated/memories';
      path: '/memories';
      fullPath: '/memories';
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge';
      path: '/knowledge';
      fullPath: '/knowledge';
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/chat': {
      id: '/_authenticated/chat';
      path: '/chat';
      fullPath: '/chat';
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute;
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute;
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute;
  AuthenticatedMetricsRoute: typeof AuthenticatedMetricsRoute;
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedMetricsRoute: AuthenticatedMetricsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
